"""set book_chapter add title column

Revision ID: 02e6a026b6fd
Revises: 5af2ad6a9dc9
Create Date: 2025-09-22 03:38:07.934151

"""
from typing import Sequence, Union

import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02e6a026b6fd'
down_revision: Union[str, None] = '5af2ad6a9dc9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book_chapter', sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('book_chapter', 'title')
    # ### end Alembic commands ###
