"""set book_chapter content text's length = 65535

Revision ID: 17f4adee2358
Revises: efaa5e99513c
Create Date: 2025-09-22 02:47:42.298190

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17f4adee2358'
down_revision: Union[str, None] = 'efaa5e99513c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
