"""delete book cover column

Revision ID: 5af2ad6a9dc9
Revises: 956defbf617a
Create Date: 2025-09-22 03:10:56.210449

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '5af2ad6a9dc9'
down_revision: Union[str, None] = '956defbf617a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('book', 'cover')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('cover', mysql.VARCHAR(length=255), nullable=False))
    # ### end Alembic commands ###
