@BASE_URL = http://localhost:8000
@Token = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ7XCJpZFwiOiAxLCBcImVtYWlsXCI6IFwiMzA5MjE3NjU5MUBxcS5jb21cIiwgXCJ1c2VybmFtZVwiOiBcInFpYW5yZW5uaVwiLCBcImF2YXRhclwiOiBcIlwiLCBcImlzX2FjdGl2ZVwiOiB0cnVlfSIsImV4cCI6MTc1ODcwMDU3Ny44NDUwMTM2fQ.w3Ynhlh3ESIFhkHLUKTPYYpLOSPkc9leyWyt3Wi03_s
###
GET {{BASE_URL}}/book/chapter/1
Accept: application/json
Authorization: {{Token}}

###
@book_id =1
@chapter_index = 1
GET {{BASE_URL}}/book/chapter/{{book_id}}/{{chapter_index}}
Accept: application/json
Authorization:  {{Token}}

###
GET {{BASE_URL}}/shelf/get
Accept:  application/json
Authorization:  {{Token}}

###
POST  {{BASE_URL}}/shelf/add
Accept:  application/json
Authorization:  {{Token}}

{
    "book_id": 1
}